@extends('layouts.app')
@section('title','Secure Checkout — Trendora')
@section('content')
@php $discount=(float)session('coupon_discount',0); @endphp
<section class="tr-page tr-checkout-page"><div class="tr-shell">
<div class="tr-page-head"><div><span class="tr-eyebrow">Secure checkout</span><h1>Complete your order</h1><p>Live shipping and tax rules are calculated from your delivery address.</p></div><a class="btn btn-outline-light" href="{{ route('cart.index') }}"><i class="fa-solid fa-arrow-left me-2"></i>Back to cart</a></div>
@if($minimumOrder>0 && (float)$cart->subtotal<$minimumOrder)<div class="alert alert-warning rounded-4 border-0">Minimum checkout amount is {{ App\Models\Setting::get('currency_symbol','Rs') }} {{ number_format($minimumOrder,2) }}. Add more items before placing the order.</div>@endif
<div class="tr-checkout-steps" data-checkout-steps><button class="active" type="button" data-step-button="1"><span>1</span>Address</button><button type="button" data-step-button="2"><span>2</span>Shipping</button><button type="button" data-step-button="3"><span>3</span>Payment</button><button type="button" data-step-button="4"><span>4</span>Review</button></div>
<form action="{{ route('checkout.process') }}" method="POST" id="checkoutForm">@csrf<input type="hidden" name="shipping_method_id" id="shippingMethodId" value="{{ old('shipping_method_id',$quote['shipping_method']['id']) }}">
<div class="row g-4 align-items-start"><div class="col-lg-8"><div class="tr-card tr-checkout-panel">
<section data-checkout-step="1"><div class="tr-section-title"><div><span>Step 1</span><h3>Delivery address</h3></div><i class="fa-solid fa-location-dot"></i></div>
@if($addresses->isNotEmpty())<div class="tr-saved-addresses mb-4">@foreach($addresses as $address)<button type="button" class="tr-saved-address {{ $address->is_default?'active':'' }}" data-address="{{ e(json_encode(['name'=>$address->name,'phone'=>$address->phone,'address'=>$address->address_line,'city'=>$address->city,'state'=>$address->state,'zip'=>$address->zip,'country'=>$address->country])) }}"><strong>{{ $address->label }}</strong><span>{{ $address->address_line }}, {{ $address->city }}</span>@if($address->is_default)<small>Default</small>@endif</button>@endforeach</div>@endif
@php $d=$addresses->firstWhere('is_default',true) ?: $addresses->first(); @endphp
<div class="row g-3"><div class="col-md-6"><label class="form-label">Full name</label><input class="form-control" data-field="name" name="shipping_name" value="{{ old('shipping_name',$d?->name ?? $user->name) }}" required></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" type="email" name="shipping_email" value="{{ old('shipping_email',$user->email) }}" required></div><div class="col-md-6"><label class="form-label">Phone</label><input class="form-control" data-field="phone" name="shipping_phone" value="{{ old('shipping_phone',$d?->phone ?? $user->phone) }}" required></div><div class="col-12"><label class="form-label">Street address</label><input class="form-control" data-field="address" name="shipping_address" value="{{ old('shipping_address',$d?->address_line ?? $user->address) }}" required></div><div class="col-md-4"><label class="form-label">City</label><input class="form-control" data-field="city" name="shipping_city" value="{{ old('shipping_city',$d?->city ?? $user->city) }}" required></div><div class="col-md-4"><label class="form-label">State / region</label><input class="form-control" data-field="state" id="shippingState" name="shipping_state" value="{{ old('shipping_state',$d?->state ?? $user->state) }}"></div><div class="col-md-4"><label class="form-label">ZIP / postal code</label><input class="form-control" data-field="zip" name="shipping_zip" value="{{ old('shipping_zip',$d?->zip ?? $user->zip) }}"></div><div class="col-12"><label class="form-label">Country</label><input class="form-control" data-field="country" id="shippingCountry" name="shipping_country" value="{{ old('shipping_country',$d?->country ?? $user->country ?? App\Models\Setting::get('checkout_default_country','Pakistan')) }}" required></div></div>
<div class="tr-step-actions"><span></span><button class="btn btn-primary" type="button" data-checkout-next id="toShipping">Calculate shipping <i class="fa-solid fa-arrow-right ms-2"></i></button></div></section>
<section class="d-none" data-checkout-step="2"><div class="tr-section-title"><div><span>Step 2</span><h3>Shipping method</h3><small class="text-muted" id="shippingRegionLabel">Available for your delivery address</small></div><i class="fa-solid fa-truck-fast"></i></div><div id="shippingMethods"><div class="text-muted py-4">Calculating available methods…</div></div><div class="tr-step-actions"><button class="btn btn-outline-light" type="button" data-checkout-prev>Back</button><button class="btn btn-primary" type="button" data-checkout-next>Continue to payment <i class="fa-solid fa-arrow-right ms-2"></i></button></div></section>
<section class="d-none" data-checkout-step="3"><div class="tr-section-title"><div><span>Step 3</span><h3>Payment method</h3></div><i class="fa-regular fa-credit-card"></i></div><div class="tr-payment-grid">@php $paymentMethods=collect([['cod','fa-money-bill-wave','Cash on delivery','Pay when your order arrives'],['wallet','fa-wallet','Store credit','Balance: '.App\Models\Setting::get('currency_symbol','Rs').' '.number_format(auth()->user()->store_credit,2)],['jazzcash','fa-mobile-screen','JazzCash','Configured JazzCash flow'],['easypaisa','fa-mobile-screen-button','EasyPaisa','Configured EasyPaisa flow'],['stripe','fa-credit-card','Card / Stripe','Secure Stripe payment'],['paypal','fa-paypal','PayPal','Continue to PayPal checkout']])->reject(fn($m)=>($m[0]==='cod' && App\Models\Setting::get('checkout_cod_enabled','on')!=='on') || ($m[0]==='wallet' && App\Models\Setting::get('checkout_wallet_enabled','on')!=='on'))->values(); @endphp@foreach($paymentMethods as $i=>$method)<label class="tr-payment-option {{ $i===0?'active':'' }}"><input type="radio" name="payment_method" value="{{ $method[0] }}" {{ $i===0?'checked':'' }} required><i class="fa-solid {{ $method[1] }}"></i><span><strong>{{ $method[2] }}</strong><small>{{ $method[3] }}</small></span><b class="fa-solid fa-circle-check"></b></label>@endforeach</div><div class="tr-step-actions"><button class="btn btn-outline-light" type="button" data-checkout-prev>Back</button><button class="btn btn-primary" type="button" data-checkout-next>Review order <i class="fa-solid fa-arrow-right ms-2"></i></button></div></section>
<section class="d-none" data-checkout-step="4"><div class="tr-section-title"><div><span>Step 4</span><h3>Review & place order</h3></div><i class="fa-solid fa-shield-halved"></i></div><div class="tr-review-block"><h6>Delivery details</h6><p id="checkoutReviewAddress" class="text-muted mb-0"></p></div><div class="tr-review-block"><h6>Shipping</h6><p id="checkoutReviewShipping" class="text-muted mb-0">{{ $quote['shipping_method']['name'] }}</p></div><div class="tr-review-block"><h6>Payment</h6><p id="checkoutReviewPayment" class="text-muted mb-0">Cash on delivery</p></div>@if(App\Models\Setting::get('checkout_notes_enabled','on')==='on')<div class="tr-review-block"><label class="form-label">Order notes <span class="text-muted">(optional)</span></label><textarea class="form-control" name="notes" rows="3">{{ old('notes') }}</textarea></div>@endif @if(App\Models\Setting::get('checkout_terms_required','on')==='on')<div class="form-check mt-3"><input class="form-check-input" id="termsCheck" name="terms_accepted" value="1" type="checkbox" required><label class="form-check-label" for="termsCheck">I agree to the <a href="{{ route('pages.terms') }}" target="_blank">terms</a> and <a href="{{ route('pages.returns') }}" target="_blank">returns policy</a>.</label></div>@endif<div class="tr-step-actions"><button class="btn btn-outline-light" type="button" data-checkout-prev>Back</button><button class="btn btn-primary btn-lg" type="submit" id="placeOrderBtn"><i class="fa-solid fa-lock me-2"></i>Place order · Rs <span data-grand-total>{{ number_format($quote['total'],2) }}</span></button></div></section>
</div></div>
<div class="col-lg-4"><aside class="tr-card tr-order-summary"><div class="d-flex justify-content-between align-items-center mb-3"><h4 class="mb-0">Order summary</h4><span class="tr-chip">{{ $cart->items_count }} items</span></div><div class="tr-summary-items">@foreach($cart->items as $item)<div class="tr-summary-product"><img src="{{ $item->product->thumbnail_url }}" alt=""><div><strong>{{ Str::limit($item->product->name,42) }}</strong><span>Qty {{ $item->quantity }}</span></div><b>Rs {{ number_format($item->total,2) }}</b></div>@endforeach</div><div class="tr-summary-totals"><div><span>Subtotal</span><strong>Rs {{ number_format($cart->subtotal,2) }}</strong></div>@if($discount>0)<div class="text-success"><span>Discount</span><strong>−Rs {{ number_format($discount,2) }}</strong></div>@endif<div><span id="taxLabel">{{ $quote['tax_name'] ?: 'Tax' }}{{ $quote['tax_rate'] ? ' ('.rtrim(rtrim(number_format($quote['tax_rate'],4),'0'),'.').'%)' : '' }}</span><strong>Rs <span data-tax>{{ number_format($quote['tax'],2) }}</span></strong></div><div><span>Shipping</span><strong>Rs <span data-shipping>{{ number_format($quote['shipping'],2) }}</span></strong></div><div class="total"><span>Total</span><strong>Rs <span data-grand-total>{{ number_format($quote['total'],2) }}</span></strong></div></div><div class="tr-secure-note"><i class="fa-solid fa-shield-halved"></i><span><strong>Server-calculated totals</strong>Shipping and tax are recalculated before the order is created.</span></div></aside></div></div>
</form></div></section>
@endsection
@push('scripts')
<script>
(function(){
 const endpoint=@json(route('checkout.quote')), csrf=document.querySelector('meta[name="csrf-token"]').content, country=document.getElementById('shippingCountry'), state=document.getElementById('shippingState'), holder=document.getElementById('shippingMethods'), hidden=document.getElementById('shippingMethodId');
 const money=n=>Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
 function render(data){holder.innerHTML='';data.methods.forEach((m,i)=>{const checked=String(m.id??'')===String(hidden.value??'') || (!hidden.value&&i===0);if(checked)hidden.value=m.id??'';const eta=m.min_days||m.max_days?` · ${m.min_days??'?'}–${m.max_days??'?'} days`:'';holder.insertAdjacentHTML('beforeend',`<label class="tr-choice ${checked?'active':''}"><input type="radio" name="shipping_choice" value="${m.id??''}" ${checked?'checked':''}><div><strong>${m.name}</strong><span>${m.zone||'Delivery'}${eta}</span></div><b>${Number(m.cost)===0?'FREE':'Rs '+money(m.cost)}</b></label>`)});holder.querySelectorAll('input').forEach(el=>el.addEventListener('change',()=>{hidden.value=el.value;quote(el.value)}));applyQuote(data.quote);}
 function applyQuote(q){document.querySelectorAll('[data-tax]').forEach(e=>e.textContent=money(q.tax));document.querySelectorAll('[data-shipping]').forEach(e=>e.textContent=money(q.shipping));document.querySelectorAll('[data-grand-total]').forEach(e=>e.textContent=money(q.total));document.getElementById('taxLabel').textContent=(q.tax_name||'Tax')+(Number(q.tax_rate)?` (${Number(q.tax_rate).toFixed(2).replace(/\.00$/,'')}%)`:'');document.getElementById('checkoutReviewShipping').textContent=`${q.shipping_method.name} · ${Number(q.shipping)===0?'Free':'Rs '+money(q.shipping)}`;}
 async function quote(method=null){holder.classList.add('opacity-50');try{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrf,'Accept':'application/json'},body:JSON.stringify({country:country.value,state:state.value,shipping_method_id:method||hidden.value||null})});const data=await res.json();if(!res.ok)throw new Error(data.message||'Unable to calculate shipping');render(data);}catch(e){holder.innerHTML=`<div class="alert alert-danger">${e.message}</div>`;}finally{holder.classList.remove('opacity-50')}}
 document.getElementById('toShipping').addEventListener('click',()=>setTimeout(()=>quote(),50));document.querySelectorAll('[data-address]').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>quote(),80)));quote();
})();
</script>
@endpush
