@extends('layouts.admin') @section('title','Reports') @section('page-title','Reports') @section('content')
<div class="ad-page-head"><div><span class="ad-eyebrow">Decision intelligence</span><h2>Commerce reports</h2><p>Five dedicated reporting workspaces covering revenue, catalog, customers, stock and growth performance.</p></div><a class="btn btn-outline-light" href="{{ route('admin.analytics.commerce') }}"><i class="fa-solid fa-chart-line me-2"></i>Commerce analytics</a></div>
<div class="ad-report-grid">
<a class="ad-report-card" href="{{ route('admin.reports.sales') }}"><span><i class="fa-solid fa-chart-line"></i></span><div><small>Revenue</small><h4>Sales Report</h4><p>Orders, revenue, AOV and top products.</p></div><i class="fa-solid fa-arrow-right"></i></a>
<a class="ad-report-card" href="{{ route('admin.reports.products') }}"><span><i class="fa-solid fa-box-open"></i></span><div><small>Catalog</small><h4>Product Report</h4><p>Best sellers, SKU performance and revenue.</p></div><i class="fa-solid fa-arrow-right"></i></a>
<a class="ad-report-card" href="{{ route('admin.reports.users') }}"><span><i class="fa-solid fa-users"></i></span><div><small>Customers</small><h4>Customer Report</h4><p>Acquisition, buyers and repeat purchase signal.</p></div><i class="fa-solid fa-arrow-right"></i></a>
<a class="ad-report-card" href="{{ route('admin.reports.inventory') }}"><span><i class="fa-solid fa-boxes-stacked"></i></span><div><small>Operations</small><h4>Inventory Report</h4><p>Availability, reservations and low-stock risk.</p></div><i class="fa-solid fa-arrow-right"></i></a>
<a class="ad-report-card" href="{{ route('admin.reports.marketing') }}"><span><i class="fa-solid fa-bullhorn"></i></span><div><small>Growth</small><h4>Marketing Report</h4><p>Spend, clicks, conversions and promotion usage.</p></div><i class="fa-solid fa-arrow-right"></i></a>
</div>
<div class="card p-4 mt-4"><div class="d-flex justify-content-between align-items-center flex-wrap gap-3"><div><h5 class="mb-1">Portable data exports</h5><p class="text-muted mb-0">Download clean CSV files for spreadsheets, BI tools or accounting workflows.</p></div><div class="d-flex flex-wrap gap-2">@foreach(['sales'=>'Sales','products'=>'Products','customers'=>'Customers','inventory'=>'Inventory','marketing'=>'Marketing'] as $key=>$label)<a class="btn btn-sm btn-outline-light" href="{{ route('admin.reports.export',$key) }}"><i class="fa-solid fa-download me-1"></i>{{ $label }}</a>@endforeach</div></div></div>
@endsection
