@extends('layouts.admin')
@section('title','Email & SMTP')
@section('page-title','Email & SMTP')
@section('content')
<div class="ad-page-head"><div><span class="ad-eyebrow">Delivery infrastructure</span><h2>Email & SMTP</h2><p>Configure the transactional mail transport without NPM. SMTP passwords are encrypted with Laravel's APP_KEY before storage.</p></div><a href="{{ route('admin.readiness.index') }}" class="btn btn-outline-light"><i class="fa-solid fa-clipboard-check me-2"></i>Production Readiness</a></div>
<div class="row g-4"><div class="col-xl-8"><form method="POST" action="{{ route('admin.mail-settings.update') }}" class="card p-4">@csrf @method('PUT')
<div class="d-flex justify-content-between align-items-center gap-3 mb-4"><div><h5 class="mb-1">SMTP override</h5><p class="text-muted small mb-0">When enabled, these values override the mail transport configured in .env for Trendora requests.</p></div><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="mail_override_enabled" value="1" id="mailOverride" {{ $values['enabled']==='on'?'checked':'' }}><label class="form-check-label" for="mailOverride">Enabled</label></div></div>
<div class="row g-3"><div class="col-md-8"><label class="form-label">SMTP host</label><input class="form-control" name="mail_host" required value="{{ old('mail_host',$values['host']) }}" placeholder="smtp.example.com"></div><div class="col-md-4"><label class="form-label">Port</label><input class="form-control" type="number" name="mail_port" required value="{{ old('mail_port',$values['port']) }}"></div>
<div class="col-md-6"><label class="form-label">Username</label><input class="form-control" name="mail_username" value="{{ old('mail_username',$values['username']) }}" autocomplete="off"></div><div class="col-md-6"><label class="form-label">Password</label><input class="form-control" type="password" name="mail_password" autocomplete="new-password" placeholder="{{ $values['has_password']?'Saved — leave blank to keep it':'Enter SMTP password' }}"></div>
<div class="col-md-4"><label class="form-label">Encryption</label><select class="form-select" name="mail_scheme"><option value="">Auto / none</option><option value="tls" {{ $values['scheme']==='tls'?'selected':'' }}>TLS</option><option value="ssl" {{ $values['scheme']==='ssl'?'selected':'' }}>SSL</option></select></div><div class="col-md-8"><label class="form-label">From email</label><input class="form-control" type="email" name="mail_from_address" required value="{{ old('mail_from_address',$values['from_address']) }}"></div><div class="col-12"><label class="form-label">From name</label><input class="form-control" name="mail_from_name" required value="{{ old('mail_from_name',$values['from_name']) }}"></div></div>
<div class="d-flex justify-content-end mt-4"><button class="btn btn-primary"><i class="fa-solid fa-floppy-disk me-2"></i>Save SMTP settings</button></div></form></div>
<div class="col-xl-4"><div class="card p-4 mb-4"><span class="ad-eyebrow">Launch sequence</span><h5 class="mt-2">Email checklist</h5><div class="ad-list-row"><div><strong>1. Save SMTP</strong><small>Use a verified provider and sender.</small></div></div><div class="ad-list-row"><div><strong>2. Send test</strong><small>Production Readiness sends a real message.</small></div></div><div class="ad-list-row"><div><strong>3. Verify templates</strong><small>Check order confirmation and shipped templates.</small></div></div><a class="btn btn-outline-light w-100 mt-3" href="{{ route('admin.templates.emails') }}">Open templates</a></div><div class="card p-4"><h6>Security</h6><p class="text-muted small mb-0">The password field is never echoed back to the browser. Saving a new password encrypts it using the current APP_KEY.</p></div></div></div>
@endsection
