@extends('layouts.admin')
@section('title','Newsletter')
@section('page-title','Newsletter Audience')
@section('content')
<div class="ad-page-head"><div><span class="ad-eyebrow">Audience</span><h2>Newsletter subscribers</h2><p>Real storefront subscriptions, opt-out state and CSV export in one place.</p></div><a class="btn btn-outline-light" href="{{ route('admin.newsletter.export') }}"><i class="fa-solid fa-file-csv me-2"></i>Export active CSV</a></div>
<div class="ad-stat-grid mb-4"><div class="ad-stat"><span>Subscribed</span><strong>{{ number_format($stats['subscribed']) }}</strong><i class="fa-solid fa-envelope-circle-check"></i></div><div class="ad-stat"><span>Unsubscribed</span><strong>{{ number_format($stats['unsubscribed']) }}</strong><i class="fa-solid fa-envelope-open"></i></div><div class="ad-stat"><span>Total records</span><strong>{{ number_format($stats['total']) }}</strong><i class="fa-solid fa-users"></i></div></div>
<form class="ad-filterbar mb-3" method="GET"><input class="form-control" name="q" value="{{ request('q') }}" placeholder="Email or name"><select class="form-select" name="status"><option value="">All statuses</option><option value="subscribed" @selected(request('status')==='subscribed')>Subscribed</option><option value="unsubscribed" @selected(request('status')==='unsubscribed')>Unsubscribed</option></select><span></span><button class="btn btn-primary" type="submit">Filter</button></form>
<div class="card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Email</th><th>Name</th><th>Source</th><th>Status</th><th>Subscribed</th><th class="text-end">Actions</th></tr></thead><tbody>@forelse($subscribers as $subscriber)<tr><td><strong>{{ $subscriber->email }}</strong></td><td>{{ $subscriber->name ?: '—' }}</td><td>{{ ucfirst(str_replace('_',' ',$subscriber->source)) }}</td><td><span class="ad-status {{ $subscriber->status==='subscribed'?'is-active':'is-inactive' }}">{{ $subscriber->status }}</span></td><td>{{ $subscriber->subscribed_at?->format('d M Y, h:i A') ?: '—' }}</td><td><div class="d-flex justify-content-end gap-2"><form method="POST" action="{{ route('admin.newsletter.toggle',$subscriber) }}">@csrf<button class="btn btn-sm btn-outline-light" type="submit">{{ $subscriber->status==='subscribed'?'Unsubscribe':'Reactivate' }}</button></form><form method="POST" action="{{ route('admin.newsletter.destroy',$subscriber) }}" onsubmit="return confirm('Delete this subscriber record?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" type="submit" aria-label="Delete {{ $subscriber->email }}"><i class="fa-regular fa-trash-can"></i></button></form></div></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-5">No newsletter subscribers yet.</td></tr>@endforelse</tbody></table></div></div><div class="mt-3">{{ $subscribers->links() }}</div>
@endsection
