@extends('layouts.admin')
@section('title','Order '.$order->order_number) @section('page-title','Order Workspace')
@section('content')
<div class="ad-page-head"><div><a class="ad-back" href="{{ route('admin.orders.index') }}">← Orders</a><h2>{{ $order->order_number }}</h2><p>Customer, fulfilment, payment and status timeline in one workspace.</p></div><div class="d-flex gap-2 flex-wrap"><a class="btn btn-outline-light" target="_blank" href="{{ route('admin.orders.preview',$order) }}">Preview invoice</a><a class="btn btn-primary" href="{{ route('admin.orders.invoice',$order) }}">Download PDF</a></div></div>
<div class="row g-4"><div class="col-xl-8">
<div class="card p-4 mb-4"><div class="d-flex justify-content-between align-items-center mb-3"><h4 class="mb-0">Order items</h4><span class="ad-status is-{{ $order->order_status }}">{{ ucfirst($order->order_status) }}</span></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Product</th><th>Variation</th><th>Warehouse</th><th>Qty</th><th class="text-end">Total</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td><strong>{{ $item->product_name }}</strong><small class="d-block text-muted">{{ $item->product_sku ?: 'No SKU' }}</small></td><td>{{ $item->variation?->attribute_value ?: '—' }}</td><td>{{ $item->warehouse?->name ?: 'Legacy stock' }}</td><td>{{ $item->quantity }}</td><td class="text-end">Rs {{ number_format($item->total,2) }}</td></tr>@endforeach</tbody></table></div></div>
<div class="card p-4"><h4>Status timeline</h4><div class="mt-3">@forelse($order->statusHistory->sortByDesc('created_at') as $event)<div class="ad-list-row"><div><strong>{{ $event->from_status ? ucfirst($event->from_status).' → ' : '' }}{{ ucfirst($event->to_status) }}</strong><small>{{ $event->note ?: 'Status updated' }} · {{ $event->user?->name ?: 'System' }}</small></div><small>{{ $event->created_at->format('d M Y H:i') }}</small></div>@empty<div class="text-muted py-3">No timeline events recorded yet.</div>@endforelse</div></div>
</div><div class="col-xl-4">
<div class="card p-4 mb-4 ad-sticky-card"><form method="POST" action="{{ route('admin.orders.status',$order) }}">@csrf @method('PUT')<h4>Order state</h4><label class="form-label mt-3">Status</label><select name="status" class="form-select">@foreach(['pending','processing','shipped','delivered','cancelled'] as $s)<option value="{{ $s }}" @selected($order->order_status===$s)>{{ ucfirst($s) }}</option>@endforeach</select><label class="form-label mt-3">Internal note</label><textarea class="form-control" rows="3" name="note" placeholder="Optional timeline note"></textarea><button class="btn btn-primary mt-3 w-100">Update status</button></form><hr><div class="ad-mini-metric"><span>Payment</span><strong>{{ ucfirst($order->payment_status) }}</strong></div><div class="ad-mini-metric"><span>Subtotal</span><strong>Rs {{ number_format($order->subtotal,2) }}</strong></div><div class="ad-mini-metric"><span>{{ $order->tax_name ?: 'Tax' }}</span><strong>Rs {{ number_format($order->tax,2) }}</strong></div><div class="ad-mini-metric"><span>{{ $order->shipping_method_name ?: 'Shipping' }}</span><strong>Rs {{ number_format($order->shipping_cost,2) }}</strong></div><div class="ad-mini-metric"><span>Discount</span><strong>−Rs {{ number_format($order->discount,2) }}</strong></div>@if($order->refunded_amount>0)<div class="ad-mini-metric"><span>Refunded</span><strong class="ad-finance-negative">−Rs {{ number_format($order->refunded_amount,2) }}</strong></div>@endif<div class="ad-mini-metric"><span>Total</span><strong>Rs {{ number_format($order->total,2) }}</strong></div><div class="d-grid gap-2 mt-3">@if($order->payment_status!=='paid' && $order->payment_status!=='refunded')<form method="POST" action="{{ route('admin.finance.mark-paid',$order) }}">@csrf<button class="btn btn-outline-success w-100">Mark payment paid</button></form>@endif<a class="btn btn-outline-light" href="{{ route('admin.finance.refunds',['order'=>$order->id]) }}">Open refund center</a></div></div>
<div class="card p-4 mb-4"><h4>Delivery</h4><p class="mb-1"><strong>{{ $order->shipping_name }}</strong></p><p class="text-muted">{{ $order->shipping_address }}<br>{{ $order->shipping_city }} {{ $order->shipping_state }} {{ $order->shipping_zip }}<br>{{ $order->shipping_country }}</p><small class="text-muted d-block">{{ $order->shipping_phone }}</small><small class="text-muted">{{ $order->shipping_email }}</small></div>
<div class="card p-4"><h4>Refunds</h4>@forelse($order->refunds as $refund)<div class="ad-list-row"><div><strong>{{ $refund->refund_number }}</strong><small>{{ ucfirst($refund->method) }}</small></div><b>Rs {{ number_format($refund->amount,2) }}</b></div>@empty<p class="text-muted mb-0">No refunds recorded.</p>@endforelse</div>
</div></div>
@endsection
