@extends('layouts.admin')
@section('title','Backups')
@section('page-title','Backup Center')
@section('content')
<div class="ad-page-head"><div><span class="ad-eyebrow">Recovery operations</span><h2>Backup center</h2><p>Create downloadable archives, monitor backup storage and configure the schedule. Database restore from the web UI is intentionally disabled for safety.</p></div><a class="btn btn-outline-light" href="{{ route('admin.backup.schedule') }}"><i class="fa-regular fa-clock me-2"></i>Schedule</a></div>
@if(!$backupAvailable)<div class="alert alert-warning border-0 rounded-4" role="alert"><strong><i class="fa-solid fa-triangle-exclamation me-2"></i>php-zip is not enabled.</strong> The rest of Trendora can run, but backup creation requires <code>ZipArchive</code>. Enable the PHP zip extension on the server first.</div>@endif
<div class="ad-stat-grid mb-4"><div class="ad-stat"><span>Total backups</span><strong>{{ number_format($stats['total']) }}</strong><i class="fa-solid fa-box-archive"></i></div><div class="ad-stat"><span>Total size</span><strong>@php $size=$stats['total_size']??0; echo $size>1048576?number_format($size/1048576,2).' MB':($size>1024?number_format($size/1024,2).' KB':$size.' B'); @endphp</strong><i class="fa-solid fa-hard-drive"></i></div><div class="ad-stat"><span>Last backup</span><strong style="font-size:16px">{{ $stats['last_backup'] ? date('d M Y, h:i A',$stats['last_backup']) : 'Not yet' }}</strong><i class="fa-regular fa-clock"></i></div><div class="ad-stat"><span>Engine</span><strong>{{ $backupAvailable ? 'Ready' : 'Zip missing' }}</strong><i class="fa-solid fa-shield-halved"></i></div></div>
<div class="d-flex flex-wrap gap-2 mb-4">
<form method="POST" action="{{ route('admin.backup.create') }}">@csrf<input type="hidden" name="type" value="database"><button class="btn btn-primary" type="submit" @disabled(!$backupAvailable)><i class="fa-solid fa-database me-2"></i>Database backup</button></form>
<form method="POST" action="{{ route('admin.backup.create') }}">@csrf<input type="hidden" name="type" value="files"><button class="btn btn-outline-light" type="submit" @disabled(!$backupAvailable)><i class="fa-regular fa-file-zipper me-2"></i>Files backup</button></form>
@if($backups)<form method="POST" action="{{ route('admin.backup.delete-all') }}" class="ms-md-auto" onsubmit="return confirm('Delete all stored backup archives?')">@csrf @method('DELETE')<button class="btn btn-outline-danger" type="submit"><i class="fa-regular fa-trash-can me-2"></i>Delete all</button></form>@endif
</div>
<div class="card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Archive</th><th>Type</th><th>Size</th><th>Created</th><th class="text-end">Actions</th></tr></thead><tbody>@forelse($backups as $backup)<tr><td><strong><i class="fa-regular fa-file-zipper me-2 text-warning"></i>{{ $backup['name'] }}</strong></td><td><span class="ad-status is-active">{{ ucfirst($backup['type']) }}</span></td><td>@php $size=$backup['size']; echo $size>1048576?number_format($size/1048576,2).' MB':($size>1024?number_format($size/1024,2).' KB':$size.' B'); @endphp</td><td>{{ date('d M Y, h:i A',$backup['created_at']) }}</td><td><div class="d-flex justify-content-end gap-2"><a class="btn btn-sm btn-outline-light" href="{{ route('admin.backup.download',$backup['name']) }}" aria-label="Download {{ $backup['name'] }}"><i class="fa-solid fa-download"></i></a><form method="POST" action="{{ route('admin.backup.delete',$backup['name']) }}" onsubmit="return confirm('Delete this backup archive?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" type="submit" aria-label="Delete {{ $backup['name'] }}"><i class="fa-regular fa-trash-can"></i></button></form></div></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-5">No backup archives found.</td></tr>@endforelse</tbody></table></div></div>
<div class="card p-4 mt-4"><div class="d-flex gap-3 align-items-start"><span class="ad-icon-square"><i class="fa-solid fa-life-ring"></i></span><div><h5 class="mb-1">Restore procedure</h5><p class="text-muted mb-0">For a production restore, enable maintenance mode, download the required archive, restore the database/files through your hosting or deployment tooling, run <code>php artisan optimize:clear</code>, then verify the store with <code>php artisan trendora:doctor --strict</code> before reopening traffic.</p></div></div></div>
@endsection
