@extends('layouts.app')
@section('title','Order '.$order->order_number.' — Trendora')
@section('content')
<section class="tr-page"><div class="tr-shell"><div class="tr-page-head"><div><span class="tr-eyebrow">Order workspace</span><h1>{{ $order->order_number }}</h1><p>Placed {{ $order->created_at->format('d M Y, h:i A') }} · {{ ucfirst($order->order_status) }}</p></div><div class="d-flex gap-2 flex-wrap"><a class="btn btn-outline-light" href="{{ route('user.order.tracking',$order) }}"><i class="fa-solid fa-truck-fast me-2"></i>Track</a><a class="btn btn-primary" target="_blank" href="{{ route('user.order.invoice',$order) }}"><i class="fa-solid fa-file-pdf me-2"></i>Invoice</a></div></div>
<div class="row g-4"><div class="col-xl-8"><div class="tr-card p-4 mb-4"><div class="d-flex justify-content-between align-items-center mb-3"><h4 class="mb-0">Items</h4><span class="tr-chip">{{ $order->items->sum('quantity') }} units</span></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Product</th><th>Qty</th><th>Price</th><th class="text-end">Total</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td><strong>{{ $item->product_name }}</strong>@if($item->variation)<small class="d-block text-muted">{{ $item->variation->attribute_name }}: {{ $item->variation->attribute_value }}</small>@endif</td><td>{{ $item->quantity }}</td><td>Rs {{ number_format($item->price,2) }}</td><td class="text-end">Rs {{ number_format($item->total,2) }}</td></tr>@endforeach</tbody></table></div></div>
<div class="tr-card p-4"><h4>Status timeline</h4><div class="tr-stack mt-3">@forelse($order->statusHistory->sortByDesc('created_at') as $event)<div class="tr-review-block"><div class="d-flex justify-content-between gap-3"><strong>{{ $event->from_status ? ucfirst($event->from_status).' → ' : '' }}{{ ucfirst($event->to_status) }}</strong><small class="text-muted">{{ $event->created_at->format('d M, H:i') }}</small></div>@if($event->note)<p class="text-muted mb-0 mt-1">{{ $event->note }}</p>@endif</div>@empty<div class="text-muted">Timeline starts with your next status update.</div>@endforelse</div></div></div>
<div class="col-xl-4"><div class="tr-card p-4 mb-4"><h4>Payment summary</h4><div class="tr-summary-totals mt-3"><div><span>Subtotal</span><strong>Rs {{ number_format($order->subtotal,2) }}</strong></div>@if($order->discount>0)<div class="text-success"><span>Discount</span><strong>−Rs {{ number_format($order->discount,2) }}</strong></div>@endif<div><span>{{ $order->tax_name ?: 'Tax' }}</span><strong>Rs {{ number_format($order->tax,2) }}</strong></div><div><span>{{ $order->shipping_method_name ?: 'Shipping' }}</span><strong>Rs {{ number_format($order->shipping_cost,2) }}</strong></div>@if($order->refunded_amount>0)<div><span>Refunded</span><strong>−Rs {{ number_format($order->refunded_amount,2) }}</strong></div>@endif<div class="total"><span>Total</span><strong>Rs {{ number_format($order->total,2) }}</strong></div></div><div class="tr-secure-note mt-3"><i class="fa-solid fa-credit-card"></i><span><strong>{{ ucfirst($order->payment_status) }}</strong>{{ strtoupper($order->payment_gateway ?: 'N/A') }}</span></div></div>
<div class="tr-card p-4 mb-4"><h4>Delivery address</h4><p class="mt-3 mb-1"><strong>{{ $order->shipping_name }}</strong></p><p class="text-muted mb-2">{{ $order->shipping_address }}<br>{{ $order->shipping_city }} {{ $order->shipping_state }} {{ $order->shipping_zip }}<br>{{ $order->shipping_country }}</p><small class="text-muted d-block">{{ $order->shipping_phone }}</small><small class="text-muted">{{ $order->shipping_email }}</small></div>
@if($order->refunds->isNotEmpty())<div class="tr-card p-4"><h4>Refund history</h4>@foreach($order->refunds as $refund)<div class="tr-review-block mt-3"><div class="d-flex justify-content-between"><strong>{{ $refund->refund_number }}</strong><b>Rs {{ number_format($refund->amount,2) }}</b></div><small class="text-muted">{{ ucfirst($refund->status) }} · {{ $refund->processed_at?->format('d M Y') }}</small></div>@endforeach</div>@endif</div></div></div></section>
@endsection
