@extends('layouts.app')
@section('title','Returns & Refunds — Trendora')
@section('content')
<section class="tr-page"><div class="tr-shell"><div class="tr-page-head tr-reveal"><div><span class="tr-eyebrow">After-sales</span><h1>Returns & refunds</h1><p>Request, track and review your after-sales cases.</p></div>@if($eligibleOrders->isNotEmpty())<button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#returnModal">New request</button>@endif</div>
<div class="tr-account-grid">@include('frontend.partials.account-nav')<div class="tr-stack">
@forelse($returns as $return)<a class="tr-card tr-list-card tr-reveal" href="{{ route('user.returns.show',$return) }}"><div><span class="tr-chip">{{ strtoupper($return->type) }}</span><h5 class="mt-2 mb-1">{{ $return->request_number }}</h5><p class="mb-0 text-muted">Order {{ $return->order->order_number }} · {{ $return->reason }}</p></div><div class="text-end"><span class="tr-status {{ $return->status }}">{{ str_replace('_',' ',$return->status) }}</span><strong class="d-block mt-2">{{ App\Models\Setting::get('currency_symbol','Rs') }} {{ number_format($return->requested_amount,2) }}</strong></div></a>@empty<div class="tr-empty tr-card"><i class="fa-solid fa-arrow-rotate-left"></i><h4>No return requests</h4><p>Eligible shipped or delivered orders can be submitted here.</p></div>@endforelse
<div>{{ $returns->links() }}</div></div></div></div></section>
@if($eligibleOrders->isNotEmpty())<div class="modal fade" id="returnModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content tr-modal"><form method="POST" action="{{ route('user.returns.store') }}">@csrf<div class="modal-header"><h5>Start return/refund request</h5><button class="btn-close btn-close-white" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-7"><label class="form-label">Order</label><select class="form-select" name="order_id" required>@foreach($eligibleOrders as $order)<option value="{{ $order->id }}">{{ $order->order_number }} — {{ App\Models\Setting::get('currency_symbol','Rs') }} {{ number_format($order->total,2) }}</option>@endforeach</select></div><div class="col-md-5"><label class="form-label">Request type</label><select class="form-select" name="type"><option value="return">Return item/order</option><option value="refund">Refund request</option></select></div><div class="col-12"><label class="form-label">Reason</label><select class="form-select" name="reason" required><option>Changed my mind</option><option>Wrong item received</option><option>Damaged or defective</option><option>Item not as described</option><option>Missing item</option><option>Other</option></select></div><div class="col-12"><label class="form-label">Details</label><textarea class="form-control" name="details" rows="4" placeholder="Tell us what happened..."></textarea></div></div></div><div class="modal-footer"><button class="btn btn-outline-light" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Submit request</button></div></form></div></div></div>@endif
@endsection
