<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\{DraftOrder,Order,OrderItem,PaymentTransaction,Product,User};use App\Notifications\CommerceNotification;use App\Services\InventoryService;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class DraftOrderController extends Controller{
 public function index(Request $r){$q=DraftOrder::with('customer')->withCount('items')->latest();if($r->filled('status'))$q->where('status',$r->status);if($r->filled('q')){$term=$r->q;$q->where(fn($x)=>$x->where('draft_number','like',"%$term%")->orWhere('customer_name','like',"%$term%")->orWhere('customer_email','like',"%$term%"));}$drafts=$q->paginate(20)->withQueryString();$stats=['draft'=>DraftOrder::where('status','draft')->count(),'sent'=>DraftOrder::where('status','sent')->count(),'converted'=>DraftOrder::where('status','converted')->count(),'value'=>DraftOrder::whereIn('status',['draft','sent'])->sum('total')];return view('admin.draft-orders.index',compact('drafts','stats'));}
 public function create(){return view('admin.draft-orders.form',['draft'=>new DraftOrder,'customers'=>User::where('role','!=','admin')->orderBy('name')->get(['id','name','email','phone']),'products'=>Product::with(['variations'=>fn($q)=>$q->where('status',true)])->where('status',true)->orderBy('name')->get()]);}
 public function store(Request $r){$d=$this->validated($r);$draft=DB::transaction(function()use($d){$draft=DraftOrder::create($this->payload($d)+['draft_number'=>DraftOrder::generateNumber(),'created_by'=>auth()->id()]);$this->syncItems($draft,$d['items']);return $draft;});return redirect()->route('admin.draft-orders.show',$draft)->with('success','Draft order created.');}
 public function show(DraftOrder $draftOrder){$draftOrder->load(['customer','items.product','items.variation','convertedOrder','creator']);return view('admin.draft-orders.show',compact('draftOrder'));}
 public function edit(DraftOrder $draftOrder){abort_if($draftOrder->status==='converted',422,'Converted drafts cannot be edited.');$draftOrder->load('items');return view('admin.draft-orders.form',['draft'=>$draftOrder,'customers'=>User::where('role','!=','admin')->orderBy('name')->get(['id','name','email','phone']),'products'=>Product::with(['variations'=>fn($q)=>$q->where('status',true)])->where('status',true)->orderBy('name')->get()]);}
 public function update(Request $r,DraftOrder $draftOrder){abort_if($draftOrder->status==='converted',422);$d=$this->validated($r);DB::transaction(function()use($draftOrder,$d){$draftOrder->update($this->payload($d));$draftOrder->items()->delete();$this->syncItems($draftOrder,$d['items']);});return redirect()->route('admin.draft-orders.show',$draftOrder)->with('success','Draft order updated.');}
 public function status(Request $r,DraftOrder $draftOrder){$d=$r->validate(['status'=>'required|in:draft,sent,cancelled']);abort_if($draftOrder->status==='converted',422);$draftOrder->update($d);return back()->with('success','Draft status updated.');}
 public function convert(DraftOrder $draftOrder,InventoryService $inventory){abort_unless(in_array($draftOrder->status,['draft','sent']),422);abort_unless($draftOrder->customer_id && $draftOrder->shipping_address && $draftOrder->shipping_city && $draftOrder->shipping_country,422,'Customer and shipping details are required before conversion.');$draftOrder->load('items.product','items.variation','customer');$order=DB::transaction(function()use($draftOrder,$inventory){$order=Order::create(['user_id'=>$draftOrder->customer_id,'order_number'=>Order::generateOrderNumber(),'subtotal'=>$draftOrder->subtotal,'discount'=>$draftOrder->discount,'tax'=>$draftOrder->tax,'tax_name'=>'Draft order tax','tax_rate'=>0,'shipping_cost'=>$draftOrder->shipping,'total'=>$draftOrder->total,'shipping_name'=>$draftOrder->customer_name?:$draftOrder->customer->name,'shipping_email'=>$draftOrder->customer_email?:$draftOrder->customer->email,'shipping_phone'=>$draftOrder->customer_phone?:$draftOrder->customer->phone,'shipping_address'=>$draftOrder->shipping_address,'shipping_city'=>$draftOrder->shipping_city,'shipping_state'=>$draftOrder->shipping_state,'shipping_zip'=>$draftOrder->shipping_zip,'shipping_country'=>$draftOrder->shipping_country,'notes'=>$draftOrder->notes,'payment_status'=>'pending','order_status'=>'pending','payment_gateway'=>'manual']);foreach($draftOrder->items as $item){$warehouse=$inventory->deduct($item->product,$item->variation,$item->quantity,$order->order_number);OrderItem::create(['order_id'=>$order->id,'product_id'=>$item->product_id,'product_variation_id'=>$item->product_variation_id,'warehouse_id'=>$warehouse,'product_name'=>$item->title,'product_sku'=>$item->sku,'quantity'=>$item->quantity,'price'=>$item->unit_price,'total'=>$item->line_total]);}$order->statusHistory()->create(['user_id'=>auth()->id(),'to_status'=>'pending','note'=>'Converted from '.$draftOrder->draft_number]);PaymentTransaction::create(['order_id'=>$order->id,'gateway'=>'manual','type'=>'charge','status'=>'pending','amount'=>$order->total,'currency'=>$draftOrder->currency,'note'=>'Created from draft order']);$draftOrder->update(['status'=>'converted','converted_order_id'=>$order->id]);return $order;});$draftOrder->customer?->notify(new CommerceNotification('Order created','Your order '.$order->order_number.' was created by our team.',route('user.order.detail',$order->id),'fa-file-invoice'));return redirect()->route('admin.orders.show',$order->id)->with('success','Draft converted to live order.');}
 public function destroy(DraftOrder $draftOrder){abort_if($draftOrder->status==='converted',422);$draftOrder->delete();return redirect()->route('admin.draft-orders.index')->with('success','Draft order deleted.');}
 private function validated(Request $r){return $r->validate(['customer_id'=>'nullable|exists:users,id','customer_name'=>'required|string|max:255','customer_email'=>'nullable|email|max:255','customer_phone'=>'nullable|string|max:40','shipping_address'=>'nullable|string|max:1000','shipping_city'=>'nullable|string|max:120','shipping_state'=>'nullable|string|max:120','shipping_zip'=>'nullable|string|max:30','shipping_country'=>'nullable|string|max:120','currency'=>'required|string|max:10','discount'=>'nullable|numeric|min:0','tax'=>'nullable|numeric|min:0','shipping'=>'nullable|numeric|min:0','notes'=>'nullable|string|max:3000','expires_at'=>'nullable|date','items'=>'required|array|min:1','items.*.product_id'=>'required|exists:products,id','items.*.product_variation_id'=>'nullable|exists:product_variations,id','items.*.quantity'=>'required|integer|min:1|max:999','items.*.unit_price'=>'nullable|numeric|min:0']);}
 private function payload($d){return collect($d)->only(['customer_id','customer_name','customer_email','customer_phone','shipping_address','shipping_city','shipping_state','shipping_zip','shipping_country','currency','discount','tax','shipping','notes','expires_at'])->all();}
 private function syncItems(DraftOrder $draft,array $items){$subtotal=0;foreach($items as $row){$p=Product::findOrFail($row['product_id']);$v=!empty($row['product_variation_id'])?$p->variations()->findOrFail($row['product_variation_id']):null;$price=(float)($row['unit_price']??($v?->price??$p->price));$line=round($price*(int)$row['quantity'],2);$draft->items()->create(['product_id'=>$p->id,'product_variation_id'=>$v?->id,'title'=>$p->name.($v?' · '.$v->attribute_value:''),'sku'=>$v?->sku??$p->sku,'quantity'=>$row['quantity'],'unit_price'=>$price,'line_total'=>$line]);$subtotal+=$line;}$total=max(0,$subtotal-(float)$draft->discount+(float)$draft->tax+(float)$draft->shipping);$draft->update(['subtotal'=>$subtotal,'total'=>$total]);}
}
