<?php
namespace App\Http\Controllers\Admin;use App\Http\Controllers\Controller;use App\Models\{GiftCard,GiftCardTransaction,User,WalletTransaction};use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class GiftCardController extends Controller{
 public function index(Request $r){$q=GiftCard::with('purchaser')->withCount('transactions')->latest();if($r->filled('q')){$t=$r->q;$q->where(fn($x)=>$x->where('code','like',"%$t%")->orWhere('recipient_email','like',"%$t%"));}$cards=$q->paginate(20)->withQueryString();$stats=['active'=>GiftCard::where('status','active')->count(),'issued'=>GiftCard::sum('initial_balance'),'balance'=>GiftCard::where('status','active')->sum('current_balance')];$customers=User::where('role','!=','admin')->orderBy('name')->get(['id','name','email']);return view('admin.gift-cards.index',compact('cards','stats','customers'));}
 public function store(Request $r){$d=$r->validate(['amount'=>'required|numeric|min:1','currency'=>'required|string|max:10','purchaser_user_id'=>'nullable|exists:users,id','recipient_name'=>'nullable|string|max:255','recipient_email'=>'nullable|email|max:255','message'=>'nullable|string|max:1000','expires_at'=>'nullable|date|after:today']);$code='TR-'.strtoupper(Str::random(4)).'-'.strtoupper(Str::random(6));$card=GiftCard::create(['code'=>$code,'initial_balance'=>$d['amount'],'current_balance'=>$d['amount'],'currency'=>$d['currency'],'status'=>'active','purchaser_user_id'=>$d['purchaser_user_id']??null,'recipient_name'=>$d['recipient_name']??null,'recipient_email'=>$d['recipient_email']??null,'message'=>$d['message']??null,'expires_at'=>$d['expires_at']??null,'created_by'=>auth()->id()]);$card->transactions()->create(['user_id'=>$d['purchaser_user_id']??null,'type'=>'issue','amount'=>$d['amount'],'balance_after'=>$d['amount'],'note'=>'Gift card issued by admin']);return back()->with('success','Gift card '.$code.' issued.');}
 public function adjust(Request $r,GiftCard $giftCard){$d=$r->validate(['amount'=>'required|numeric','note'=>'required|string|max:500']);DB::transaction(function()use($giftCard,$d){$locked=GiftCard::whereKey($giftCard->id)->lockForUpdate()->firstOrFail();$old=(float)$locked->current_balance;$new=max(0,$old+(float)$d['amount']);$actual=$new-$old;$locked->update(['current_balance'=>$new,'status'=>$new>0?'active':'redeemed']);$locked->transactions()->create(['type'=>'adjustment','amount'=>$actual,'balance_after'=>$new,'note'=>$d['note']]);});return back()->with('success','Gift card balance adjusted.');}
 public function toggle(GiftCard $giftCard){$giftCard->update(['status'=>$giftCard->status==='disabled'?'active':'disabled']);return back()->with('success','Gift card status changed.');}
 public function walletAdjust(Request $r,User $user){$d=$r->validate(['amount'=>'required|numeric|not_in:0','note'=>'required|string|max:500']);DB::transaction(function()use($user,$d){$locked=User::whereKey($user->id)->lockForUpdate()->firstOrFail();$old=(float)$locked->store_credit;$new=max(0,$old+(float)$d['amount']);$actual=$new-$old;$locked->update(['store_credit'=>$new]);WalletTransaction::create(['user_id'=>$locked->id,'processed_by'=>auth()->id(),'type'=>$actual>=0?'credit':'debit','amount'=>$actual,'balance_after'=>$new,'note'=>$d['note']]);});return back()->with('success','Customer store credit updated.');}
}
