<?php
namespace App\Http\Controllers\Admin;use App\Http\Controllers\Controller;use App\Models\{Inventory,Product,PurchaseOrder,Supplier,Warehouse};use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class PurchaseOrderController extends Controller{
 public function index(){return view('admin.purchase-orders.index',['orders'=>PurchaseOrder::with(['supplier','warehouse'])->withCount('items')->latest()->paginate(20)]);}
 public function create(){return view('admin.purchase-orders.form',['purchaseOrder'=>new PurchaseOrder,'suppliers'=>Supplier::where('status',true)->orderBy('name')->get(),'warehouses'=>Warehouse::where('status',true)->orderBy('name')->get(),'products'=>Product::with(['variations'=>fn($q)=>$q->where('status',true)])->where('status',true)->orderBy('name')->get()]);}
 public function store(Request $r){$d=$r->validate(['supplier_id'=>'required|exists:suppliers,id','warehouse_id'=>'required|exists:warehouses,id','expected_at'=>'nullable|date','notes'=>'nullable|string|max:3000','items'=>'required|array|min:1','items.*.product_id'=>'required|exists:products,id','items.*.product_variation_id'=>'nullable|exists:product_variations,id','items.*.quantity'=>'required|integer|min:1','items.*.cost'=>'required|numeric|min:0']);$po=DB::transaction(function()use($d){$po=PurchaseOrder::create(['po_number'=>PurchaseOrder::generateNumber(),'supplier_id'=>$d['supplier_id'],'warehouse_id'=>$d['warehouse_id'],'expected_at'=>$d['expected_at']??null,'notes'=>$d['notes']??null,'created_by'=>auth()->id()]);$sum=0;foreach($d['items'] as $row){$total=(int)$row['quantity']*(float)$row['cost'];$po->items()->create($row+['total'=>$total]);$sum+=$total;}$po->update(['subtotal'=>$sum,'total'=>$sum]);return $po;});return redirect()->route('admin.purchase-orders.show',$po)->with('success','Purchase order created.');}
 public function show(PurchaseOrder $purchaseOrder){$purchaseOrder->load(['supplier','warehouse','items.product','items.variation','creator']);return view('admin.purchase-orders.show',compact('purchaseOrder'));}
 public function status(Request $r,PurchaseOrder $purchaseOrder){$d=$r->validate(['status'=>'required|in:draft,ordered,cancelled']);abort_if($purchaseOrder->status==='received',422);$attrs=['status'=>$d['status']];if($d['status']==='ordered'&&!$purchaseOrder->ordered_at)$attrs['ordered_at']=today();$purchaseOrder->update($attrs);return back()->with('success','Purchase order status updated.');}
 public function receive(PurchaseOrder $purchaseOrder){abort_if(in_array($purchaseOrder->status,['received','cancelled']),422);DB::transaction(function()use($purchaseOrder){$purchaseOrder->load('items.product','items.variation');foreach($purchaseOrder->items as $item){$remaining=$item->quantity-$item->received_quantity;if($remaining<=0)continue;$inv=Inventory::firstOrCreate(['warehouse_id'=>$purchaseOrder->warehouse_id,'product_id'=>$item->product_id,'product_variation_id'=>$item->product_variation_id],['sku'=>$item->variation?->sku??$item->product->sku,'quantity'=>0,'reserved_quantity'=>0,'reorder_level'=>5]);$before=$inv->quantity;$inv->increment('quantity',$remaining);$inv->movements()->create(['user_id'=>auth()->id(),'type'=>'purchase','quantity'=>$remaining,'before_quantity'=>$before,'after_quantity'=>$before+$remaining,'reference'=>$purchaseOrder->po_number,'note'=>'Purchase order receipt']);$item->update(['received_quantity'=>$item->quantity]);if($item->product_variation_id)$item->variation()->increment('stock_quantity',$remaining);else $item->product()->increment('stock_quantity',$remaining);}$purchaseOrder->update(['status'=>'received','received_at'=>today()]);});return back()->with('success','Purchase order fully received into inventory.');}
}
