<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\AdminRole;use App\Models\Permission;use Illuminate\Http\Request;use Illuminate\Support\Str;use Illuminate\Validation\Rule;
class RoleController extends Controller {
 public function index(){ $this->seedPermissions();$roles=AdminRole::with(['permissions'])->withCount('users')->get();$permissions=Permission::orderBy('group')->orderBy('name')->get()->groupBy('group');return view('admin.roles.index',compact('roles','permissions'));}
 public function store(Request $r){$d=$r->validate(['name'=>'required|string|max:100','slug'=>'nullable|string|max:120|unique:admin_roles,slug','description'=>'nullable|string|max:500','permissions'=>'nullable|array','permissions.*'=>'exists:permissions,id']);$role=AdminRole::create(['name'=>$d['name'],'slug'=>Str::slug($d['slug']??$d['name']),'description'=>$d['description']??null]);$role->permissions()->sync($d['permissions']??[]);return back()->with('success','Admin role created.');}
 public function update(Request $r,AdminRole $role){$d=$r->validate(['name'=>'required|string|max:100','slug'=>['nullable','string','max:120',Rule::unique('admin_roles','slug')->ignore($role->id)],'description'=>'nullable|string|max:500','permissions'=>'nullable|array','permissions.*'=>'exists:permissions,id']);$role->update(['name'=>$d['name'],'slug'=>Str::slug($d['slug']??$d['name']),'description'=>$d['description']??null]);$role->permissions()->sync($d['permissions']??[]);return back()->with('success','Role permissions updated.');}
 public function destroy(AdminRole $role){if($role->is_system||$role->users()->exists())return back()->with('error','System/in-use roles cannot be deleted.');$role->delete();return back()->with('success','Role deleted.');}
 private function seedPermissions(){if(Permission::exists())return;$groups=['catalog'=>['products.manage','categories.manage','inventory.manage'],'orders'=>['orders.manage','returns.manage'],'customers'=>['customers.manage','support.manage'],'marketing'=>['marketing.manage','content.manage'],'operations'=>['shipping.manage','tax.manage','reports.view'],'system'=>['staff.manage','settings.manage','security.manage']];foreach($groups as $g=>$keys)foreach($keys as $key)Permission::create(['name'=>ucwords(str_replace(['.','_'],' ',$key)),'key'=>$key,'group'=>$g]);}
}
